services:
  mongodb:
    image: mongo:7.0
    container_name: mongo
    restart: always
    volumes:
      - ./docker_data/mongo:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./docker_data/redis:/data